#!/bin/bash
set -e
install_dir=$(cd $(dirname $0) && pwd)
master_key=$($install_dir/scan-qr | base64)
plain_text=$1
attempt=0
mode=${2:-all}
while [ true ]; do
    hash=$(echo -n "$master_key $attempt $plain_text $master_key" | shasum -a 512 | xxd -p -r | base64)
    # Should have:
    #  - upper case letter
    #  - lower case letter
    #  - number
    #  - symbol
    #
    # And be 12 characters long.
    #
    if [ "$mode" == "all" ]; then
        part0=$(echo $hash | cut -b 21-24)
        part1=$(echo $hash | cut -b 31-34 | tr '[a-z]' '[A-Z]')
        part2=$(echo $hash | cut -b 41-44 | tr '[A-Z]' '[a-z]')
        part3=$(echo $hash | cut -b 51-54 | tr '[a-j]' '[0-9]' | tr '[A-J]' '[0-9]')
        candidate="${part0}^${part1}_${part2}#${part3}"
        echo $candidate | grep '[0-9]' | grep '[a-z]' | grep '[A-Z]' >/dev/null && echo $candidate && exit
    elif [ "$mode" == "alpha" ]; then
        candidate=$(echo $hash | cut -b 31-46 | tr '[0-9]' '[a-j]' | tr '[+/]' '[kM]')
        echo $candidate
        exit
    elif [ "$mode" == "alnum" ]; then
        candidate=$(echo $hash | cut -b 41-56 | tr '[+/]' '[t4]')
        echo $candidate
        exit
    else
        echo "Second arg 'mode' must be one of: all, alpha, alnum" >&2
    fi
    attempt=$(expr $attempt + 1)
done
