#!/bin/bash
set -e

install_dir=$(cd $(dirname $0) && pwd)

function validate_master_key {
    local key;
    local len;
    key=$1
    len=$(echo -n $key | wc -c)
    if [ $len -lt 256 ]; then
        echo "Key is too short (must be at least 2048 bits)" >&2
        false
    fi
    if [ $(echo -n $key | bzip2 | wc -c) -lt $len ]; then
        echo "Key is not random enough" >&2
        false
    fi
    if [ $(echo -n $key | gzip | wc -c) -lt $len ]; then
        echo "Key is not random enough" >&2
        false
    fi
}

echo -n "Password: " >&2
read -s password; echo "" >&2
echo "Scan master key..." >&2

master_key=$($install_dir/scan-qr | base64 -D)
validate_master_key "$master_key"

plain_text=$1
mode=${2:-all}
size=${3:-16}

attempt=0
while [ true ]; do
    hash=$(echo -n "$master_key$attempt$password$plain_text$master_key" | shasum -a 512 | xxd -p -r | base64)
    # Should have:
    #  - upper case letter
    #  - lower case letter
    #  - number
    #  - symbol
    #
    # And be $size characters long.
    #
    if [ "$mode" == "all" ]; then
        echo $hash | cut -b 1-$size | grep '[0-9]' | grep '[a-z]' | grep '[A-Z]' | grep '[/+]' && break
    elif [ "$mode" == "lower" ]; then
        echo $hash | sed -e 's,[A-Z0-9/+=],,g' | cut -b 1-$size && break
    elif [ "$mode" == "alpha" ]; then
        echo $hash | sed -e 's,[0-9/+=],,g' | cut -b 1-$size | grep '[a-z]' | grep '[A-Z]' && break
    elif [ "$mode" == "alnum" ]; then
        echo $hash | sed -e 's,[/+=],,g' | cut -b 1-$size | grep '[0-9]' | grep '[a-z]' | grep '[A-Z]' && break
    elif [ "$mode" == "digit" ]; then
        echo $hash | sed -e 's,[A-Za-z/+=],,g' | cut -b 1-$size && break
    else
        echo "Second arg 'mode' must be one of: all, alpha, alnum, lower, digit" >&2
    fi
    attempt=$(expr $attempt + 1)
done
