#!/bin/bash
function capture_png {
    ffmpeg -y -f avfoundation -video_size 1280x720 -framerate 30 -i "0" -vframes 1 -f rawvideo -c:v png $* 2>/dev/null
}

function qrdecode {
    zbarimg -q PNG:${1:--} | sed -e 's,^QR-Code:,,'
}

function try_frame {
     capture_png - | qrdecode
}

while [ true ]; do
    code=$(try_frame)
    if [ "$code" != "" ]; then
        echo $code
        exit
    fi
done
